[package]
name = "dungeoneer-types"
description = "Common data structures and types for the Dungeoneer application"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
